baseURL = "https://unibo-oop.github.io/lab-slides"
languageCode = "en-us"
title = "Laboratorio di Programmazione ad Oggetti"
disableKinds = ["sitemap", "RSS"]
theme = "reveal-hugo"
publishDir = "build"
ignoreFiles = ['.*generator.md$']

# uncomment for browsing at file:///
# relativeURLs = true
# uglyURLs = true

[author]
name = "Danilo Pianini"

# currently only the unsafe mode for goldmark is supported
[markup.goldmark.renderer]
unsafe = true

# choose between Hugo compile-time or Highlight.js
# syntax highlighting for code inside of code fences
[markup.highlight]
#codeFences = false  # use highlight.js
codeFences = true  # use hugo highlighting at compile time
style = "xcode"  # set a style for hugo highlighting

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
history = true
theme = "white"
highlight_theme = "default"
slide_number = true
transition = "slide"
transition_speed = "fast"
custom_theme = "custom-theme.scss"
custom_theme_compile = true
width = '1920'
height = '1080'

[params.reveal_hugo.custom_theme_options]
targetPath = "css/custom-theme.css"
enableSourceMap = true

[[params.reveal_hugo.mermaid]]
startOnLoad = false
# theme = "default"
# fontFamily = "Inconsolata"
#useMaxWidth = true
